# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_game_gm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import protocol_msgid_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_game_gm.proto',
  package='ftproto',
  serialized_pb='\n\x16protocol_game_gm.proto\x12\x07\x66tproto\x1a\x14protocol_msgid.proto\"_\n\x0b\x43SGMCommand\x12\x34\n\x05msgid\x18\x01 \x01(\x0e\x32\x0f.ftproto.EMsgID:\x14\x45MsgID_CS_GM_COMMAND\x12\r\n\x05token\x18\x02 \x02(\x04\x12\x0b\n\x03\x63md\x18\x03 \x02(\t\"m\n\x0fSCSendClientMsg\x12\x39\n\x05msgid\x18\x01 \x01(\x0e\x32\x0f.ftproto.EMsgID:\x19\x45MsgID_SC_SEND_CLIENT_MSG\x12\x0e\n\x06\x63md_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t')




_CSGMCOMMAND = _descriptor.Descriptor(
  name='CSGMCommand',
  full_name='ftproto.CSGMCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='ftproto.CSGMCommand.msgid', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=19001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='ftproto.CSGMCommand.token', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='ftproto.CSGMCommand.cmd', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=152,
)


_SCSENDCLIENTMSG = _descriptor.Descriptor(
  name='SCSendClientMsg',
  full_name='ftproto.SCSendClientMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='ftproto.SCSendClientMsg.msgid', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=10300,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd_id', full_name='ftproto.SCSendClientMsg.cmd_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='ftproto.SCSendClientMsg.context', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=154,
  serialized_end=263,
)

_CSGMCOMMAND.fields_by_name['msgid'].enum_type = protocol_msgid_pb2._EMSGID
_SCSENDCLIENTMSG.fields_by_name['msgid'].enum_type = protocol_msgid_pb2._EMSGID
DESCRIPTOR.message_types_by_name['CSGMCommand'] = _CSGMCOMMAND
DESCRIPTOR.message_types_by_name['SCSendClientMsg'] = _SCSENDCLIENTMSG

class CSGMCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CSGMCOMMAND

  # @@protoc_insertion_point(class_scope:ftproto.CSGMCommand)

class SCSendClientMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCSENDCLIENTMSG

  # @@protoc_insertion_point(class_scope:ftproto.SCSendClientMsg)


# @@protoc_insertion_point(module_scope)
