# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_test.proto',
  package='ftproto',
  serialized_pb='\n\x13protocol_test.proto\x12\x07\x66tproto\"%\n\x06\x43SPing\x12\r\n\x05token\x18\x01 \x02(\x04\x12\x0c\n\x04time\x18\x02 \x02(\x03')




_CSPING = _descriptor.Descriptor(
  name='CSPing',
  full_name='ftproto.CSPing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='ftproto.CSPing.token', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='ftproto.CSPing.time', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['CSPing'] = _CSPING

class CSPing(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CSPING

  # @@protoc_insertion_point(class_scope:ftproto.CSPing)


# @@protoc_insertion_point(module_scope)
